version: 2

models:
  - name: sales_fact
    description: "Fact table recording sales transaction"
    columns:
      - name: transaction_id
        description: "Primary key for each sales transaction"
        tests:
          - unique
          - not_null
      
      - name: product_id
        description: "Foreign key to dim_product"
        tests: 
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: store_id
        description: "Foreign key to dim_store"
        tests:
          - not_null
          - relationships:
              to: ref('dim_store')
              field: store_id

      - name: transaction_date
        description: "Date when the transaction occurred"
        tests: 
          - not_null
          - relationships:
              to: ref('dim_date')
              field: calendar_date

      - name: quantity
        description: "Quantity of products sold"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "{{ quantity }} > 0"

      - name: total_price
        description: "Total price for transaction"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "{{ total_price }} >= 0"